baseurl: ''
default_lang: en
description: A curated list of awesome embodied AI papers with code implementations
exclude_from_langs: []
github_username: LJoson
kramdown:
  hard_wrap: false
  input: GFM
lang: en
lang_names:
  en: English
  zh: 中文
languages:
- en
- zh
markdown: kramdown
show_downloads: true
theme: jekyll-theme-minimal
title: Awesome Embodied AI
url: https://glimmerlab.github.io/Awesome-Embodied-AI
