title: Awesome Embodied AI Papers
description: 一个专注于体感AI领域最新论文的在线资源库
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/GlimmerLab/Awesome-Embodied-AI/archive/main.zip
  tar_url: https://github.com/GlimmerLab/Awesome-Embodied-AI/archive/main.tar.gz
  repository_url: https://github.com/GlimmerLab/Awesome-Embodied-AI
  owner_url: https://github.com/GlimmerLab
  owner_name: GlimmerLab