name: Sync Docs

on:
  # 在daily_update工作流完成后触发
  workflow_run:
    workflows: ["Daily Paper Update"]
    types:
      - completed
  # 允许手动触发
  workflow_dispatch:

# 添加权限设置
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync:
    name: Sync to Docs
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Sync content to docs
        run: |
          python scripts/sync_docs.py

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          # 自动生成 token
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Jekyll
        uses: actions/jekyll-build-gh-pages@v1
        with:
          source: ./docs
          destination: ./_site
          future: false
          unpublished: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site
          retention-days: 1  # 只保留1天

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: _site
          clean: true  # 部署前清理目标分支

      - name: Debug - Deployment status
        run: |
          echo "Deployment status: ${{ steps.deployment.outputs.outcome }}"
          echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"